### ISSUE TITLE
join market not working

### ISSUE THREAD

**Issue by nickjdenton-dev** [Fonta1n3/FullyNoded-Server#6]
Last login: Sat Dec  7 00:16:44 on ttys000
/Users/xx/.fullynoded/startJoinMarket.sh ; exit;

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
Library/Application Support/joinmarket: No such file or directory
Creating SSL self signed cert.
/var/folders/06/bjjv73td5sqdfxjq5_85nv8h0000gn/T/AppTranslocation/9C95F0AD-D261-446A-9108-E9BCD3069929/d/FullyNoded-Server.app/Contents/Resources/StartJm.command: line 16: cd: /Users/xx/Library/Application Support/joinmarket/ssl: No such file or directory
...+..+++++++++++++++++++++++++++++++++++++++*..........+......+.....+....+.....+....+..+...+......+....+...........+....+...+..+...+....+...........+....+......+..+.............+++++++++++++++++++++++++++++++++++++++*...+......+.....+..........+..+.+.........+..+..........+...+..........................+.+.........+..+....+.....+...+...+..........+...+..+...+....+..+...+...+.........+....+......+........+...+...+..........+......+........+.+.....+.+......+............+..+.+..............+.............+..................+...+..+.......+.....+......+............+............+...+...........................+...............+...+.......+........+............+......................+.....+......++++++
.+.+..............+......+.......+..............+.+...+...........+.+..+++++++++++++++++++++++++++++++++++++++*...+......+.....+....+......+.....+++++++++++++++++++++++++++++++++++++++*.+......+...+.....+......+...+..........+..+...+.......+...............+........+......+................+...........+....+..............+......+....+.........+.....+.......+.........+...........+.+..................+.....+.......+..............+.+.....+..........+..+............+...+.+.....+.+...+...........+.+...+...+........+.........+..........+..+.+..+............+...............+......+....+........+..........+.................+.+..+......+.+......+........++++++
-----
req warning: No value provided for subject name attribute "C", skipped
req warning: No value provided for subject name attribute "ST", skipped
req warning: No value provided for subject name attribute "L", skipped
req warning: No value provided for subject name attribute "O", skipped
req warning: No value provided for subject name attribute "OU", skipped
cd /Users/xx/.fullynoded/JoinMarket/joinmarket-0.9.11
source jmvenv/bin/activate
cd scripts
python jmwalletd.py
Traceback (most recent call last):
  File "/Users/xx/.fullynoded/JoinMarket/joinmarket-0.9.11/scripts/jmwalletd.py", line 4, in <module>
    from jmclient import (load_program_config, jm_single,
ModuleNotFoundError: No module named 'jmclient'
logout

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by Fonta1n3** [comment]
Fixed

**Comment by nickjdenton-dev** [comment]
HypeSent from my iPhoneOn Dec 18, 2024, at 3:54 PM, Fontaine ***@***.***> wrote:﻿
Fixed
